### ISSUE TITLE
not working on android 7 and lower

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#19]
On android 7 and lower app crashes on start and i have not clue why! (with android 8/8.1 it is working fine!)

ava.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
        at com.reactlibrary.storage.Storage.Init(Storage.java:71)
        at com.reactlibrary.storage.Storage.<init>(Storage.java:50)
        at com.reactlibrary.RNVasernModule.<init>(RNVasernModule.java:30)
        at com.reactlibrary.RNVasernPackage.createNativeModules(RNVasernPackage.java:17)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:85)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1173)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1143)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1085)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:117)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
        at java.lang.Thread.run(Thread.java:761)

That what i get under logcat.

**Comment by hieunc229** [comment]
Thanks for the details. I'll look into the problem and will publish a fix ASAP

**Comment by apppro123** [comment]
I'm SO SORRY, this error was because of me (and not updating this package)!!!
I'm so sorry. Thank you still for your help!
